### ISSUE TITLE
CloudWatchLogs - adjusting the width of data columns gets readjusted after scroll

### ISSUE THREAD

**Issue by hunterwerlla** [aws/aws-toolkit-jetbrains#1692]

**Comment by abrooksv** [comment]
Since we know the format is fixed (timestamp), can we just per-caulcate the size of a Label with the timestamp (Just use Instant.now()) and use that as the width instead of trying to be fancy?

**Comment by hunterwerlla** [comment]
it's not fixed width so that doesn't work 100%, we could do something more correct though

**Comment by abrooksv** [comment]
> it's not fixed width so that doesn't work 100%, we could do something more correct though

Ah, not monospaced font, right
