### ISSUE TITLE
Lambda Debugger takes me to _pydev_execfile.py and crashes

### ISSUE THREAD

**Issue by Spothedog1** [aws/aws-toolkit-jetbrains#1871]
**Describe the bug**
I have been using AWS Toolkit for Pycharm for a couple months now. I'll set a breakpoint in my code and press debug and get taken to the breakpoint. It was working great last night but today I tried picking up where I left off and ran the exact same code again in debug mode and was taken to a file _pydev_execfile.py where a breakpoint was set on the line

`exec(compile(contents+"\n", file, 'exec'), glob, loc)`

now I tried running multiple other functions in debug mode and they're all throwing the same error. I've run all these functions lots of times before today and they've always worked. 

**To reproduce**
1. Set breakpoint in Lambda function
2. Debug function
3. Crash 

**Expected behavior**
1. Set breakpoint in Lambda function
2. Debug function
3. Taken to breakpoint

**Screenshots**
![_pydev_execfile.py](https://user-images.githubusercontent.com/7429961/85643456-29a5bf80-b662-11ea-9c49-ccef3ceb3f98.png)
![my function](https://user-images.githubusercontent.com/7429961/85643458-2c081980-b662-11ea-9d1e-e7ae68711abb.png)

**Your Environment**
- OS: macOS Catalina 10.15.4 
- JetBrains product: Pycharm
- JetBrains product version: 2019.3.5
- AWS Toolkit version: 1.16-193
- SAM CLI version: 0.51.0
- JVM/Python version: 3.8

**Additional context**
It looks like there is an error in _pydev_execfile when trying to import sys. 
I'm also using Layers, recently I installed the requests module onto my layer and I think that is what may have broken it although it worked once when I ran it with the requests module.

**Comment by Spothedog1** [comment]
UPDATE: I upgraded to

- JetBrains product version: 2020.1.2
- AWS Toolkit version: 1.16-201

Now the error shows up in the debug console rather than taking me to the breakpoint in _pydev_execfile.py 
![image](https://user-images.githubusercontent.com/7429961/85647173-df294080-b66b-11ea-81da-aa9ee2fedd76.png)

**Comment by abrooksv** [comment]
Sam cli needs to be updated to deal with new lambda runtime. https://github.com/awslabs/aws-sam-cli/issues/2069

**Comment by mhart** [comment]
The Lambda runtimes have been rolled back (for now) – so this issue should be fixed. Hopefully SAM CLI will be ready when they update again

**Comment by Spothedog1** [comment]
@mhart @abrooksv It's working now, thanks.

**Comment by Spothedog1** [comment]
Hi I updated to SAM CLI 1.0.0 and this issue is popping up again. Then I tried rolling back to SAM CLI 0.51.0 and the issue persists. 


    OS: macOS Catalina 10.15.6
    JetBrains product: Pycharm
    JetBrains product version: 2020.2
    AWS Toolkit version: 1.17-202
    SAM CLI version: 1.0.0
    JVM/Python version: 3.8

**Comment by mhart** [comment]
Rolling back won't work – the images have all been updated and the old code will no longer work – only SAM CLI 1.0.0 and later will work.

Are you sure you're running 1.0.0?

**Comment by Spothedog1** [comment]
![image](https://user-images.githubusercontent.com/7429961/89848775-f86f4900-db54-11ea-898b-21e4df3f650d.png)

**Comment by mhart** [comment]
Is there a chance there's another version lying around that this plugin might be picking up? (I'm not familiar with how it looks for `sam`)

Does the same error occur if you debug from `sam` directly (without using Pycharm)?

**Comment by Spothedog1** [comment]
Good call, I had installed the sam-cli using brew and pip at different times. I had the pip version upgraded but not brew, upgrading the brew version solved the issue. Thanks.
