### ISSUE TITLE
Amazon Q plugin for Intelij not working after activation

### ISSUE THREAD

**Issue by rodux** [aws/aws-toolkit-jetbrains#6039]
---
Toolkit: Amazon Q For JetBrains 3.94.252
OS: Linux 6.14.0-29-generic
IDE: IntelliJ IDEA Ultimate Edition 252

After activating business account, the plugin window seems stuck at "Fetching Q Developer profiles...this make take a minute" and in the log I have this error:

java.lang.IllegalStateException: You don't have access to the resource
	at software.aws.toolkits.jetbrains.services.amazonq.profile.QRegionProfileManager.listRegionProfiles(QRegionProfileManager.kt:115)
	at software.aws.toolkits.jetbrains.services.codewhisperer.customization.DefaultCodeWhispererModelConfigurator.listCustomizations$lambda$17(CodeWhispererModelConfigurator.kt:126)
	at software.aws.toolkits.jetbrains.services.amazonq.QUtilsKt.calculateIfIamIdentityCenterConnection(QUtils.kt:28)
	at software.aws.toolkits.jetbrains.services.amazonq.QUtilsKt.calculateIfIamIdentityCenterConnection(QUtils.kt:21)
	at software.aws.toolkits.jetbrains.services.codewhisperer.customization.DefaultCodeWhispererModelConfigurator.listCustomizations(CodeWhispererModelConfigurator.kt:124)
	at software.aws.toolkits.jetbrains.services.codewhisperer.startup.CodeWhispererProjectStartupActivity.runActivity$lambda$1$lambda$0(CodeWhispererProjectStartupActivity.kt:65)
	at software.aws.toolkits.jetbrains.utils.ThreadingUtilsKt.pluginAwareExecuteOnPooledThread$lambda$4$lambda$3(ThreadingUtils.kt:88)
	at io.opentelemetry.context.Context.lambda$wrap$2(Context.java:253)
	at software.aws.toolkits.jetbrains.utils.ThreadingUtilsKt.pluginAwareExecuteOnPooledThread$lambda$4(ThreadingUtils.kt:88)
	at com.intellij.openapi.application.impl.ApplicationImpl$5.call(ApplicationImpl.java:356)
	at com.intellij.util.concurrency.ContextCallable.lambda$call$1(ContextCallable.java:86)
	at com.intellij.util.concurrency.ContextCallable.call(ContextCallable.java:95)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at com.intellij.util.concurrency.ChildContext$runInChildContext$1.invoke(propagation.kt:167)
	at com.intellij.util.concurrency.ChildContext$runInChildContext$1.invoke(propagation.kt:167)
	at com.intellij.util.concurrency.ChildContext.runInChildContext(propagation.kt:173)
	at com.intellij.util.concurrency.ChildContext.runInChildContext(propagation.kt:167)
	at com.intellij.util.concurrency.ContextRunnable.run(ContextRunnable.java:27)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:735)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:732)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:732)
	at java.base/java.lang.Thread.run(Thread.java:1583)

Anything for me to do to make this plugin to work?
Thanks

**Comment by pexa-hr** [comment]
I am also facing the same issue today.

**Comment by jmak24** [comment]
Any update on this? Experiencing the same issue

**Comment by Andrew-Omelchenko** [comment]
I am also facing the same issue.
Amazon Q (3.96.252)
Thanks.

**Comment by Andrew-Omelchenko** [comment]
The problem was resolved after updating the plugin version.
Amazon Q (3.97.252)

**Comment by gdromero** [comment]
Same issue with

Toolkit: Amazon Q For JetBrains 3.97.252
OS: Mac OS X 15.6.1
IDE: IntelliJ IDEA Ultimate Edition 252

**Comment by romankh** [comment]
Not resolved for me, having the same issue with plugin version 3.97.252

**Comment by artellador** [comment]
Same here
3.98.252
IntelliJ Ultimate 2025.2.5
Ubuntu 22.04.5 LTS

**Comment by artellador** [comment]
Funny: now it works 😆
